

// 67 CLAUSE THIS FILE WAS AUTOGENERATED DO NOT EDIT

import { Fixed, VarOrTerminated, Schema, parse_tokens, Parsed_clause } from "../../../compiler/src_ts/utils/new_parser.ts";

function must<T>(not_null: T | null | undefined, message: string): T {
  if (not_null === null || not_null === undefined) {
    throw new Error(message);
  }
  return not_null;
}

export class point {
  schema = {
    loops: new VarOrTerminated(null /* TODO */, [] /* TODO */, {
      forever: new Fixed(0, [] /* TODO */, undefined),
      each: new Fixed(1, [] /* TODO */, undefined),
    }),
  };
  parse(tokens: string[]) {

    const parsed = parse_tokens(tokens, this.schema);

    type Focus_type = {
      value: string[];
      children: {
        [key: string]: Parsed_clause<Schema["any"]>[];
      } | null;
    }

    let focus: Focus_type = {
      value: [],
      children: parsed,
    };

    let result; // TypeScript better infer ts

    let parent_focus = focus ;
    let parent_result; // TypeScript better infer ts
    if (focus.children != null && "loops" in focus.children && focus.children["loops"].length > 0) {
      focus = must(focus.children?.["loops"]?.[0], "focus clause not found");
      if (focus.children != null && "forever" in focus.children && focus.children["forever"].length > 0) {
        result = {
        ["kind"]: "forever" as const,
        };

      }

      if (focus.children != null && "each" in focus.children && focus.children["each"].length > 0) {
        focus = must(focus.children?.["each"]?.[0], "focus clause not found");
        result = {
        ["kind"]: "each" as const,
        ["each"]: must(focus.value[0], "argument not found"),
        };

      }


      if (result === undefined) {
        throw new Error("clause was not provided");
      }
    
    }


    if (result === undefined) {
      throw new Error("clause was not provided");
    }
    
    return result;
  }
}

