# Import all macro modules to ensure they register with the unified registry
from . import local_macro
from . import fn_macro
from . import exists_macro
from . import param_macro
from . import access_chain_macro
from . import then_macro
from . import collection_macros
from . import comment_macros
from . import error_macros
from . import for_macro
from . import if_macro
from . import literal_value_macros
from . import noscope_macro
from . import scope_macro
from . import solution_macro
from . import utility_macros
from . import while_macro
from . import try_catch_macro
from . import bind_macro