# utils/error_types.cr
# Error type constants for machine-readable compile error categorization.

module ErrorType
  ERROR_TYPES = %w[
    EXPECTED_DO_AFTER
    EXPECTED_THEN_AFTER
    SYNTAX_ERROR
    INVALID_MACRO
    INVALID_INDENTATION

    TYPE_MISMATCH
    FIELD_TYPE_MISMATCH
    ARGUMENT_TYPE_MISMATCH
    MISSING_TYPE
    NO_SUCH_LOCAL
    NO_MATCHING_OVERLOAD
    AMBIGUOUS_OVERLOAD

    WRONG_ARG_COUNT
    MISSING_CHILD
    MISSING_BLOCK
    INVALID_STRUCTURE

    MISSING_CONTEXT
    INVALID_PLACEMENT

    UNTERMINATED_STRING

    INVALID_INT
    INVALID_FLOAT

    ASSERTION_FAILED
    UNKNOWN_ERROR
  ]

  {% for name in ERROR_TYPES %}
    {{name.id}} = {{name}}
  {% end %}
end
