let a = 5;
let b = 10;
let name1 = "Alice";
let name2 = "Bob";
console.log("Equal integers:", (an a === 5));
console.log("Not equal integers:", (an a === an b));
console.log("Ascending order:", (an a < an b));
console.log("Descending order:", (an b < an a));
console.log("String equality:", (an name1 === "Alice"));
console.log("String comparison:", (an name1 < an name2));